site_name: Livro de Receitas Vegan

theme:
  name: material
  language: pt

plugins:
  - search

nav:
  - Início: index.md

  - Pratos Principais:
      - Chow Mein: pratos-principais/chow-mein.md
      - Salada de Falafel no Forno: pratos-principais/salada-de-falafel-no-forno.md
      - Shawarma de Cogumelos: pratos-principais/shawarma-de-cogumelos.md
      - Barcos de Curgete Pizza: pratos-principais/barcos-de-curgete-pizza.md
      - Massa com Pimento Vermelho Assado: pratos-principais/massa-com-pimento-vermelho-assado.md
      - Caril Massaman: pratos-principais/caril-massaman.md
      - Bifes de Couve-flor Panados: pratos-principais/bifes-de-couve-flor-panados.md
      - Ramen de Legumes: pratos-principais/ramen-de-legumes.md

  - Sobre: sobre.md